### PR TITLE
Update autoprefixer-rails dependency to 8.0

### PR DESCRIPTION
**Pull request by tysongach**
- [Release](https://github.com/ai/autoprefixer-rails/releases/tag/8.0.0)
- [Change log](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by porada** [comment]
Hey @tysongach, thanks for the pull request.

Could you change the accepted versions to `>= 8.0` and `< 9.0`, though? I deliberately want to keep those wide open to avoid unnecessary upgrades of this gem. Autoprefixer (the core library) usually gets support for new CSS features and properties with each minor version. This way, you’ll be able to take advantage of those only with `bundle upgrade`.

**Comment by porada** [comment]
Oh, I must have misread that as `~> 8.0.0`. All good then!

**Comment by tysongach** [comment]
Thanks for reviewing and merging!

**Comment by porada** [comment]
Middleman Autoprefixer v2.9.0 is out. Thanks!

**Pull request merged**
